### ISSUE TITLE
Minor inconsistency in negative column selelection (i.e. dt[, !c('colname')] with char. vector

### ISSUE THREAD

**Issue by m-dz** [Rdatatable/data.table#2059]
Hi, I have noticed a minor (because it can be fixed with a simple `with = FALSE`) inconsistency in the negative column selection, see e.g.:

```
library(data.table)

dt <- data.table(a = 1, b = 2, c = 3)

sel_col <- c('a', 'b')
 
dt[, !sel_col]                         # Throws an "error in !sel_col : invalid argument type"
dt[, !c('a', 'b')]

dt[, !sel_col, with = FALSE]
```

Is this something that can be fixed or the cause is burried too deep?

My guess is when parcing the call dt cannot tell what `sel_col` is, thus cannot parse it correctly, am I right?

**Comment by jangorecki** [comment]
this should be fixed by amending code to any of those two
```r
dt[, !sel_col, with = FALSE]
dt[, !..sel_col]
```
when you try `dt[, sel_col]` you will see it raises error as well, although more meaningful.

**Comment by m-dz** [comment]
Thank you @jangorecki for reminding me about this! I see `..` was included in v1.11.0 (and introduced as experimental in v1.10.2). I'm still not fully getting why `!c('a', 'b')` worked while `!sel_col` didn't, but I guess this is related to how you parse dt calls, so a bit above my `R` level.

**Comment by jangorecki** [comment]
It is related to the fact that `sel_col` might be an existing column in your data.table, and then operation would be ambiguous. When you provide character values directly, then there is no risk of scoping issues, that is why it does work.

**Comment by m-dz** [comment]
Thank you for explanation.
