### ISSUE TITLE
significantly slower performance time based rolling 1.14.3

### ISSUE THREAD

**Issue by ssh352** [Rdatatable/data.table#5366]
I am a multi year data.table user and today I've seen 3 times slower performance of data.table time based rolling aggregation compared with pandas rolling aggregation. Please advise if the behavior is expected and if here is a correct place to post reproducible examples. Thanks. 

for data.table time based rolling I use non-equip join syntax. Pandas rolling I use the rolling() function.

**Comment by MichaelChirico** [comment]
@ssh352 sorry to hear about that. please spend some time to produce a minimal reprex -- barring that it doesn't make sense for us to invest time chasing rabbits in the dark.

**Comment by ssh352** [comment]
`
  library(data.table)
  library(arrow)

  set.seed(1)
  n <- 1e5
  d1 <- abs(rnorm(n, sd = 4))
  d2 <- as.integer(cumsum(d1))
  tm <- as.POSIXct("2020-01-01 09:30:00") + d2
  nIds <- 3
  tmCol <- rep(tm, nIds)
  length(tmCol)
  idCol <- rep(c("a", "b", "c"), n)
  length(idCol)

  f1 <- function() {
      dt <- data.table(tm = tmCol, v = 1, id = idCol)
      # write_parquet(dt, 'test.parquet') # use python to read this file and do the pandas rolling to compare
      dt[, tm1 := tm - 40]
      dt[, tm2 := tm]
      dt[, rowNum := .I]
      dt[dt, .(vs = sum(v)), on = .(id, rowNum <= rowNum, tm >= tm1, tm < tm2), by = .EACHI]
  }

 results <- microbenchmark::microbenchmark(
      f1(), # needs to have () otherwise f1 is not invoked
      times = 5L
  )

  results
`
it averaged 0.8 seconds for each iteration of f1()

**Comment by ssh352** [comment]
```
  import pandas as pd
  import time

  def rolling_sum(grp):
      grp["vs"] = grp.rolling('4s', on="tm")["v"].sum()
      return grp

  start = time.time()
  df = pd.read_parquet(r'test.parquet')
  df = df.sort_values(by=['tm'])
  start2 = time.time()
  df = df.groupby('id', as_index=False, group_keys=False).apply(rolling_sum)
  end = time.time()
  print(end-start)
  print(end-start2)
  ```
  for the python version it averaged about 1.3 seconds for each iteration of the rolling operation.

  for time based rolling, it appears non-equi join method is quite slower. Please advise, Thank you!

**Comment by t-wojciech** [comment]
@ssh352, did you try to use [frollsum()](https://rdatatable.gitlab.io/data.table/reference/froll.html) from data.table?

**Comment by ssh352** [comment]
> 

@t-wojciech hi, frollsum only works for row based rolling, not time based rolling.

**Comment by tlapak** [comment]
On my machine with two cores, the code you posted runs for 11 seconds. Pulling out the grouping gets it to about 7.5 s:

```R
f1 <- function() {
  dt <- data.table(tm = tmCol, v = 1, id = idCol)
  # write_parquet(dt, 'test.parquet') # use python to read this file and do the pandas rolling to compare
  dt[, tm1 := tm - 40]
  dt[, tm2 := tm]
  dt[, rowNum := .I]
  dt[dt, .(vs = sum(v)), on = .(id, rowNum <= rowNum, tm >= tm1, tm2 < tm2), by = .EACHI]
}

f2 <- function() {
  dt <- data.table(tm = tmCol, v = 1, id = idCol)
  # write_parquet(dt, 'test.parquet') # use python to read this file and do the pandas rolling to compare
  dt[, tm1 := tm - 40]
  dt[, tm2 := tm]
  dt[, rowNum := .I]
  dta <- dt[dt, .(id, rowNum, tm, i.tm1, v), on = .(id, rowNum<=rowNum, tm>=tm1, tm2<tm2)]
  dta[, .(tm=min(i.tm1), tm2=min(tm), vs=sum(v)), by=.(rowNum, id)]
}

dta <- f1()
dtb <- f2()
all.equal(dta, dtb, ignore.col.order=TRUE)
#[1] TRUE

```

(Note that defining the column `tm2` is unnecessary. I used it to slightly modify your example in order to get two different column names in the result.)

The problem is *much* worse on dev. I aborted a run at 250 s. When I changed n to 1e4 your example took 4 s, at 1e5 it took 40 s. That problem was introduced in #4491. @jangorecki, any idea what's going on with that?

**Comment by jangorecki** [comment]
It must have added an overhead, probably in some tight loop if it is so much slower.

**Comment by jangorecki** [comment]
https://github.com/Rdatatable/data.table/issues/3241 would probably address nicely time based window

**Comment by jangorecki** [comment]
This issue should be resolved by resolving root cause describe in #5371

**Comment by ssh352** [comment]
> This issue should be resolved by resolving root cause describe in #5371

https://github.com/Rdatatable/data.table/issues/5366#issuecomment-1092959070

On the same machine, this code still takes 8.4 seconds to run with data.table_1.14.10. I am afraid it is not resolved yet.

**Comment by MichaelChirico** [comment]
@ssh352 please check on current `master`. Recent data.table releases are patch-only and don't include recent fixes. Otherwise please check again when 1.15.0 is released ("very soon")
